server:
  port: 9090
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
spring:
  threads.virtual.enabled: true
  profiles:
    active: local
  application:
    name: coder
  sql:
    init:
      mode: always    
custom: 
  meta-database: mysql  # 数据库类型，不配默认 mysql。可选值：mysql / postgresql / oracle / sqlserver
  excludes: ["flyway_schema_history","coder_meta","coder_server"] #排除的表